<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Yutaka" name="com.sqa.ao.helped.CalcAreaStaticTests" tests="45" failures="0" timestamp="26 Oct 2015 22:29:54 GMT" time="0.049" errors="8">
  <testcase name="testCalcAreaStaticLL" time="0.000" classname="com.sqa.ao.helped.CalcAreaStaticTests"/>
  <testcase name="testCalcAreaStaticLL" time="0.001" classname="com.sqa.ao.helped.CalcAreaStaticTests"/>
  <testcase name="testCalcAreaStaticTS" time="0.000" classname="com.sqa.ao.helped.CalcAreaStaticTests"/>
  <testcase name="testCalcAreaStaticTS" time="0.000" classname="com.sqa.ao.helped.CalcAreaStaticTests"/>
  <testcase name="testCalcAreaStaticAP" time="0.000" classname="com.sqa.ao.helped.CalcAreaStaticTests"/>
  <testcase name="testCalcAreaStaticPN" time="0.000" classname="com.sqa.ao.helped.CalcAreaStaticTests"/>
  <testcase name="testCalcAreaStaticAP" time="0.001" classname="com.sqa.ao.helped.CalcAreaStaticTests"/>
  <testcase name="testCalcAreaStaticTS" time="0.000" classname="com.sqa.ao.helped.CalcAreaStaticTests"/>
  <testcase name="testCalcAreaStaticAP" time="0.001" classname="com.sqa.ao.helped.CalcAreaStaticTests"/>
  <testcase name="testCalcAreaStaticPN" time="0.000" classname="com.sqa.ao.helped.CalcAreaStaticTests"/>
  <testcase name="testCalcAreaStaticAP" time="0.001" classname="com.sqa.ao.helped.CalcAreaStaticTests">
    <error type="java.lang.AssertionError" message="expected [12.56] but found [6.283185307179586]">
      <![CDATA[java.lang.AssertionError: expected [12.56] but found [6.283185307179586]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at com.sqa.ao.helped.CalcAreaStaticTests.testCalcAreaStaticAP(CalcAreaStaticTests.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- testCalcAreaStaticAP -->
  <testcase name="testCalcAreaStaticAO" time="0.001" classname="com.sqa.ao.helped.CalcAreaStaticTests"/>
  <testcase name="testCalcAreaStaticAO" time="0.001" classname="com.sqa.ao.helped.CalcAreaStaticTests"/>
  <testcase name="testCalcAreaStaticLL" time="0.000" classname="com.sqa.ao.helped.CalcAreaStaticTests"/>
  <testcase name="testCalcAreaStaticLL" time="0.001" classname="com.sqa.ao.helped.CalcAreaStaticTests"/>
  <testcase name="testCalcAreaStaticTS" time="0.000" classname="com.sqa.ao.helped.CalcAreaStaticTests"/>
  <testcase name="testCalcAreaStaticAO" time="0.001" classname="com.sqa.ao.helped.CalcAreaStaticTests">
    <error type="java.lang.AssertionError" message="expected [12.56] but found [12.566370614359172]">
      <![CDATA[java.lang.AssertionError: expected [12.56] but found [12.566370614359172]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at com.sqa.ao.helped.CalcAreaStaticTests.testCalcAreaStaticAO(CalcAreaStaticTests.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- testCalcAreaStaticAO -->
  <testcase name="testCalcAreaStaticLL" time="0.002" classname="com.sqa.ao.helped.CalcAreaStaticTests"/>
  <testcase name="testCalcAreaStaticAO" time="0.023" classname="com.sqa.ao.helped.CalcAreaStaticTests">
    <error type="java.lang.AssertionError" message="expected [3.14] but found [3.141592653589793]">
      <![CDATA[java.lang.AssertionError: expected [3.14] but found [3.141592653589793]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at com.sqa.ao.helped.CalcAreaStaticTests.testCalcAreaStaticAO(CalcAreaStaticTests.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- testCalcAreaStaticAO -->
  <testcase name="testCalcAreaStaticTS" time="0.000" classname="com.sqa.ao.helped.CalcAreaStaticTests"/>
  <testcase name="testCalcAreaStaticPN" time="0.000" classname="com.sqa.ao.helped.CalcAreaStaticTests"/>
  <testcase name="testCalcAreaStaticLL" time="0.000" classname="com.sqa.ao.helped.CalcAreaStaticTests"/>
  <testcase name="testCalcAreaStaticLL" time="0.000" classname="com.sqa.ao.helped.CalcAreaStaticTests"/>
  <testcase name="testCalcAreaStaticTS" time="0.002" classname="com.sqa.ao.helped.CalcAreaStaticTests">
    <error type="java.lang.AssertionError" message="expected [3.14] but found [3.141592653589793]">
      <![CDATA[java.lang.AssertionError: expected [3.14] but found [3.141592653589793]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at com.sqa.ao.helped.CalcAreaStaticTests.testCalcAreaStaticTS(CalcAreaStaticTests.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- testCalcAreaStaticTS -->
  <testcase name="testCalcAreaStaticAP" time="0.000" classname="com.sqa.ao.helped.CalcAreaStaticTests"/>
  <testcase name="testCalcAreaStaticPN" time="0.001" classname="com.sqa.ao.helped.CalcAreaStaticTests">
    <error type="java.lang.AssertionError" message="expected [12.56] but found [12.566370614359172]">
      <![CDATA[java.lang.AssertionError: expected [12.56] but found [12.566370614359172]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at com.sqa.ao.helped.CalcAreaStaticTests.testCalcAreaStaticPN(CalcAreaStaticTests.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- testCalcAreaStaticPN -->
  <testcase name="testCalcAreaStaticPN" time="0.002" classname="com.sqa.ao.helped.CalcAreaStaticTests">
    <error type="java.lang.AssertionError" message="expected [3.14] but found [3.141592653589793]">
      <![CDATA[java.lang.AssertionError: expected [3.14] but found [3.141592653589793]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at com.sqa.ao.helped.CalcAreaStaticTests.testCalcAreaStaticPN(CalcAreaStaticTests.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- testCalcAreaStaticPN -->
  <testcase name="testCalcAreaStaticPN" time="0.000" classname="com.sqa.ao.helped.CalcAreaStaticTests"/>
  <testcase name="testCalcAreaStaticAP" time="0.002" classname="com.sqa.ao.helped.CalcAreaStaticTests">
    <error type="java.lang.AssertionError" message="expected [3.14] but found [3.141592653589793]">
      <![CDATA[java.lang.AssertionError: expected [3.14] but found [3.141592653589793]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at com.sqa.ao.helped.CalcAreaStaticTests.testCalcAreaStaticAP(CalcAreaStaticTests.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- testCalcAreaStaticAP -->
  <testcase name="testCalcAreaStaticLL" time="0.000" classname="com.sqa.ao.helped.CalcAreaStaticTests"/>
  <testcase name="testCalcAreaStaticPN" time="0.000" classname="com.sqa.ao.helped.CalcAreaStaticTests"/>
  <testcase name="testCalcAreaStaticPN" time="0.000" classname="com.sqa.ao.helped.CalcAreaStaticTests"/>
  <testcase name="testCalcAreaStaticTS" time="0.001" classname="com.sqa.ao.helped.CalcAreaStaticTests">
    <error type="java.lang.AssertionError" message="expected [12.56] but found [12.566370614359172]">
      <![CDATA[java.lang.AssertionError: expected [12.56] but found [12.566370614359172]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at com.sqa.ao.helped.CalcAreaStaticTests.testCalcAreaStaticTS(CalcAreaStaticTests.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- testCalcAreaStaticTS -->
  <testcase name="testCalcAreaStaticAO" time="0.001" classname="com.sqa.ao.helped.CalcAreaStaticTests"/>
  <testcase name="testCalcAreaStaticTS" time="0.001" classname="com.sqa.ao.helped.CalcAreaStaticTests"/>
  <testcase name="testCalcAreaStaticAO" time="0.001" classname="com.sqa.ao.helped.CalcAreaStaticTests"/>
  <testcase name="testCalcAreaStaticAP" time="0.001" classname="com.sqa.ao.helped.CalcAreaStaticTests"/>
  <testcase name="testCalcAreaStaticLL" time="0.000" classname="com.sqa.ao.helped.CalcAreaStaticTests"/>
  <testcase name="testCalcAreaStaticAO" time="0.001" classname="com.sqa.ao.helped.CalcAreaStaticTests"/>
  <testcase name="testCalcAreaStaticAO" time="0.001" classname="com.sqa.ao.helped.CalcAreaStaticTests"/>
  <testcase name="testCalcAreaStaticAP" time="0.000" classname="com.sqa.ao.helped.CalcAreaStaticTests"/>
  <testcase name="testCalcAreaStaticAO" time="0.001" classname="com.sqa.ao.helped.CalcAreaStaticTests"/>
  <testcase name="testCalcAreaStaticTS" time="0.001" classname="com.sqa.ao.helped.CalcAreaStaticTests"/>
  <testcase name="testCalcAreaStaticPN" time="0.000" classname="com.sqa.ao.helped.CalcAreaStaticTests"/>
  <testcase name="testCalcAreaStaticAP" time="0.000" classname="com.sqa.ao.helped.CalcAreaStaticTests"/>
</testsuite> <!-- com.sqa.ao.helped.CalcAreaStaticTests -->
